### ISSUE TITLE
 pyperclip issue

### ISSUE THREAD

**Issue by dztoshiba43** [rzc0d3r/ESET-KeyGen#171]
pyperclip don't work on (Python 3.12.3) !

**Comment by rzc0d3r** [comment]
Download the python version below and install without add to path and leave only PIP in the tick boxes. Install the libraries through it and run the project through it

**Comment by rzc0d3r** [comment]
I using python 3.12.2 and pyperclip works

**Comment by rzc0d3r** [comment]
what system you have?

**Comment by rzc0d3r** [comment]
and send the error logs please

**Comment by rzc0d3r** [comment]
### Description of Pyperclip

**On Windows, no additional modules are needed.**

**On Mac, this module makes use of the pbcopy and pbpaste commands, which should come with the os.**

**On Linux, this module makes use of the xclip or xsel commands, which should come with the os. Otherwise run ```sudo apt-get install xclip``` or ```sudo apt-get install xsel``` (Note: xsel does not always seem to work.)**

Otherwise on Linux, you will need the gtk or PyQt4 modules installed.

**Comment by dztoshiba43** [comment]
Windows 10 Enterprise 64-bit

![01](https://github.com/rzc0d3r/ESET-KeyGen/assets/164612768/dde35964-c355-4e15-97fe-a74d89eda35f)

**Comment by rzc0d3r** [comment]
Hmm strange. Try install older version example
```pip install pyperclip==1.8.1```

**Comment by dztoshiba43** [comment]
Same error message / don't work /
I think this is due to the fact that there are no updates to it, it stopped in 2021
(https://pypi.org/project/pyperclip/#history).

**Comment by rzc0d3r** [comment]
Try adding this folder to the root folder of the project
[pyperclip.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/15109207/pyperclip.zip)
